apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0
        ports:
        - containerPort: 27017
        imagePullPolicy: Always                  # Always :  means that Kubernetes will always pull the latest version of the image from the container registry
                                                 # IfNotPresent (Default Value) : which tells Kubernetes to use the locally cached image if it exists, otherwise pull the image
                                                 # Never : Kubernetes will never attempt to pull the image from a registry. Instead, it will rely entirely on images already present on the nodes in the cluster
